services:
  db:
    image: postgres:16-alpine
    container_name: guestara_db_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    env_file:
      - path: ./dev.env
        required: true

  app:
    image: node:22-alpine
    container_name: guestara_app_dev
    working_dir: /usr/src/app
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - path: ./dev.env
        required: true
    depends_on:
      - db


volumes:
  db_data_dev: