# Builder
FROM node:22-alpine AS builder

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable & pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

#Runtime
FROM node:22-alpine
WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./
RUN corepack enable & pnpm install --prod --frozen-lockfile

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 3000
CMD ["node", "dist/cmd/api/index.js"]